services:
  spring-boot-app:
    image: backend
    ports:
      - "0.0.0.0:8091:8091"
    environment:
      - SPRING_DATABASE_URL=jdbc:mysql://mysql:3308/api_etudiant
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "api_etudiant"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "0.0.0.0:3308:3308"
    volumes:
      - api_etudiant:/var/lib/mysql

volumes:
  api_etudiant:
